### PR TITLE
Improve zhCN trans

### PR DESCRIPTION
**Pull request by ericlogic**
机动, 机器人, 雇佣兵, etc. are uniformly revised as 佣兵, which means Mercenary in Chinese and used as the offical translate by Blizzard. This is more immersive.

### CODE REVIEW

**Comment by trickerer** [comment]
This may be better but you're doing a ton of extra changes here so please:
- Remove all those introduced extra `|` and `|r`
- Replace all those now full unicode range dots `。` back with UTF-8 ones `.`

**Comment by ericlogic** [comment]
Sorry, I originally made the change in Trinitycore-3.5-with-npcbots and then copied it to Trinity-Bots. I didn't notice the difference between them. I'll remove those introduced extra | and |r.

As for "。", this is the standard punctuation mark used in Chinese to indicate the end of a sentence. Additionally, in Chinese, the punctuation mark that serves the same function as "..." is "……".

If you wish, I can revise these punctuation marks accordingly.

**Comment by trickerer** [comment]
> Sorry, I originally made the change in Trinitycore-3.5-with-npcbots and then copied it to Trinity-Bots. I didn't notice the difference between them. I'll remove those introduced extra | and |r.

Yeah, those are my mistake actually. At some point Trinity-Bots localization files were updated but not in patched repos. Locale files will be removed from those repos in the future (probably).

> As for "。", this is the standard punctuation mark used in Chinese to indicate the end of a sentence. Additionally, in Chinese, the punctuation mark that serves the same function as "..." is "……".

Localizations are community driven and generally I'm fine with whatever works for people. There are two reason why I've brought that up:
- Punctuation changes weren't mentioned is PR description, for me they came out of nowhere (not a biggie but I'd like to avoid undocumented changes)
- You only change **some** dots to full unicode range but not all (ex. 70102). As a maintainer I want them to be uniform; or unchanged. I'll be fine with either of those

**Comment by ericlogic** [comment]
Yes, you are right.
I will review my changes and submit latter.

**Comment by ericlogic** [comment]
I reviewed all my changes and here is the change list.

机动, 机器人, 雇佣兵, etc. are uniformly revised as 佣兵, which means Mercenary in Chinese and used as the offical translate by Blizzard. This is more immersive.
Adjust the punctuation marks to conform to Chinese usage habits.
Replace "," with "，";  "." with "。";  ":" with "：";  "!" with "！ "， and remove unnecessary spaces.
Change "..." in dialogue to "……", while keeping "..." unchanged in menus.
Fixed a typo, "假如" should be "加入".

**Pull request merged**
